### PR TITLE
Add gift final price

### PR DESCRIPTION
**Pull request by ILYAGVC**
Add GiftFinalPrice.md

### CODE REVIEW

**Comment by MixV2** [comment]
Hi, thanks for the PR and sorry for the late response - would you be able to move this to the [endpoints](https://github.com/MixV2/EpicResearch/tree/master/docs/mcp/endpoints) folder, if possible? Would be better to have it there as this is not an MCP operation.

**Comment by ILYAGVC** [comment]
Hi,
Done.

**Comment by ILYAGVC** [comment]
Hi,
Done

**Comment by MixV2** [comment]
Thanks, perfect

**Pull request merged**
